#!/bin/sh

HOST=$1

if [ $# -eq 2 ]; then
  PORT=$2;
else
  PORT=5672;
fi

echo " --- Configuring registry queue to $HOST:$PORT"

qpid-config -a $HOST:$PORT add exchange direct kordapt.service-registration
qpid-config -a $HOST:$PORT add queue kordapt.service-registration --durable